version: '3'
services:
  db:
    image: mariadb:10.6
    container_name: ${PROJECT_NAME}-db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/conf/mysql:/etc/mysql/conf.d
      - ./docker/conf/mysql/dump:/docker-entrypoint-initdb.d
      - mysql-socket:/run/mysqld
    networks:
      - default  
    ports:
      - "3306:3306"
  server:
    container_name: ${PROJECT_NAME}-server
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    environment:
      WAIT_HOSTS: db:3306
      TZ: ${TZ}
    ports:
      - "8001:8001"
    depends_on:
      - db
  agent1:
    container_name: ${PROJECT_NAME}-agent1
    build:
      context: .
      dockerfile: ./docker/Dockerfile-agent
    environment:
      - EVAL_GO_POOL_SIZE=3
      - EVAL_GO_AGENT_NAME=Agent1
      - WAIT_HOSTS=server:8001
    depends_on:
      - nginx
  agent2:
    container_name: ${PROJECT_NAME}-agent2
    build:
      context: .
      dockerfile: ./docker/Dockerfile-agent
    environment:
      - EVAL_GO_POOL_SIZE=2
      - EVAL_GO_AGENT_NAME=Agent2  
      - WAIT_HOSTS=server:8001
    depends_on:
      - nginx    
  nginx:
    image: nginx:1.21-alpine
    container_name: ${PROJECT_NAME}-nginx
    environment:
      - TZ
    volumes:
      - ./:/app
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf/nginx/app-nginx.conf:/etc/nginx/templates/app-nginx.conf.template
    ports:
      - "80:80"
    depends_on:
      - server    
volumes:
  mysql-data:
  mysql-socket: