FROM golang:1.21-alpine as builder

WORKDIR /user/local/src

RUN apk --no-cache add gcc musl-dev

# dependencies
COPY ["server/go.mod", "./"]
RUN go mod download

# build
COPY agent ./
RUN go build -o ./bin/app cmd/main.go

# Runner
FROM alpine as runner
COPY --from=builder /user/local/src/bin/app /
COPY --from=ghcr.io/ufoscout/docker-compose-wait:latest /wait /wait

CMD /wait && /app